DROP TABLE IF EXISTS receita;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE receita (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  titulo TEXT NOT NULL,
  ingredientes TEXT NOT NULL,
  modo_preparo TEXT NOT NULL,
  tempo_preparo INTEGER NOT NULL DEFAULT 0,
  categoria TEXT NOT NULL DEFAULT 'outros',
  FOREIGN KEY (author_id) REFERENCES user (id)
);
